export const CHANGEPHOTOSTATE = 'CHANGEPHOTOSTATE';
export const LOGIN = 'LOGIN';
export const FETCH_LOCATION_MUSIC = 'FETCH_LOCATION_MUSIC';
export const FETCH_RECOMMEND_MUSIC = 'FETCH_RECOMMEND_MUSIC';
export const CHANGEMUSICBOXSTATE = 'CHANGEMUSICBOXSTATE';
export const DELETEMUSIC = 'DELETEMUSIC';
export const RENAME = 'RENAME';
export const CHANGEMYMUSICNAME = 'CHANGEMYMUSICNAME';

